services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        restart: unless-stopped
        volumes:
          - .:/var/www
        networks:
          - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
          - "8000:80"
        volumes:
          - .:/var/www
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
          - app-network
        depends_on:
          - backend


networks:
    app-network:
        driver: bridge
