services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        restart: unless-stopped
        depends_on:
          - db
        volumes:
          - .:/var/www
        networks:
          - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
          - "8000:80"
        volumes:
          - .:/var/www
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
          - app-network
        depends_on:
          - backend

    db:
      image: mysql:9.4
      container_name: db
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: analytics
        MYSQL_USER: analytic
        MYSQL_PASSWORD: analytic12345678
      ports:
        - "3306:3306"
      volumes:
        - ./mysql:/var/lib/mysql
      networks:
        - app-network


networks:
    app-network:
        driver: bridge

volumes:
  mysql:
